name: Deploy website to GitHub PagesAdd commentMore actions

env:
  WC_HUGO_VERSION: '0.136.5'

on:
  # Trigger the workflow every time you push to the `main` branch
@@ -44,7 +44,7 @@ jobs:
          ${{ runner.os }}-hugomod-
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with Hugo
      env:
        HUGO_ENVIRONMENT: production
@@ -54,7 +54,7 @@ jobs:
    - name: Generate Pagefind search index
      run: npx pagefind --site "public"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

@@ -69,4 +69,4 @@ jobs:
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4